apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: netology-svc
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080